# -*- coding: utf-8 -*-
"""langchain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kbggP0fZtrOuxyRqxJepTWDPe59S6Iuy
"""

!pip install langchain

from langchain.llms import HuggingFaceHub

import os

os.environ["HUGGINGFACEHUB_API_TOKEN"]="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"

prompt="whai is the conculsion for bahubali"

llm= HuggingFaceHub(
    repo_id="huggingfaceh4/zephyr-7b-alpha",
    model_kwargs={"temperature":0.5,"max_new_tokens":512}
)

print(llm.predict(prompt))